タスクトレイ上でタスクを登録できるようになりました
earlgray283/gakujo-google-calendar pull request #23
Opened 2022-01-18 16:22 UTC by Seele0709

タスクトレイでボタンを押すとGoogle Calendar上に未提出の課題を登録します。

2022-01-19 02:53 UTC, earlgray283 requested changes

2022-01-19 02:53 UTC, earlgray283 commented on app/app.go
> +	systray.Run(a.OnReady, a.OnExit)
TODO: systray.Run のエラーハンドリングの再考

2022-01-19 02:53 UTC, earlgray283 commented on app/google-calendar-api_test.go
> +		config, err = GenerateConfig()
ここで GenerateConfig() をすると壊れるので、このエラーハンドリングはあんまりよくないです。
gakujo-google-calendar は起動時に必ず token.json と .account のチェックをすることが保証されているので、ここでは素直に systray.Quit() をするのがいいと思います。

2022-01-19 02:53 UTC, earlgray283 commented on app/systray-handlers.go
> +			ReportCounter, err := a.registerReport()
register は「登録するer」なので関数の名前としてはふさわしくないです。
registReport() の typo？

2022-01-19 02:53 UTC, earlgray283 commented on app/systray-handlers.go
> +		case <-AllAdder.ClickedCh:
ここも registAll() みたいに関数化した方が可読性的に良いです

2022-01-19 02:53 UTC, earlgray283 commented on app/systray-handlers.go
> +		if row.LastSubmitDate.String() == "0001-01-01 00:00:00 +0000 UTC" {
`"0001-01-01 00:00:00 +0000 UTC"` は constant にした方がいいと思います

2022-01-19 02:53 UTC, earlgray283 commented on app/systray-handlers.go
> +				DateTime: row.EndDate.Add(-time.Hour).Format("2006-01-02T15:04:05+09:00"),
Format も constant にした方がいいと思います

2022-01-19 02:53 UTC, earlgray283 commented on app/systray-handlers.go
> +			Description: "TaskID: " + row.TaskMetadata.ID,
TaskID をユーザーが見る必要はないので、内部的に完結した方がいいと思います

2022-01-21 07:01 UTC, earlgray283 requested changes

2022-01-21 07:01 UTC, earlgray283 commented on app/systray-handlers.go
> +	added := time.Now().Format(formatAdded)
時間系の変数は `*At` が多いです
なので、今回は `addedAt` が好ましいでうs

2022-01-21 07:05 UTC, Seele0709 commented on app/systray-handlers.go
> +	err := open.Run(url)
done

2022-01-21 07:08 UTC, Seele0709 commented on app/systray-handlers.go
> +				err := AddSchedule(event, calendarId, a.srv)
done

2022-01-21 07:08 UTC, Seele0709 commented on app/systray-handlers.go
> +const dateTimeNotSubmited = "0001-01-01 00:00:00 +0000 UTC" //未提出の課題を選別するめのconst
done

2022-01-21 07:34 UTC, merged