定期実行
earlgray283/gakujo-google-calendar pull request #29
Opened 2022-01-19 13:16 UTC by mistralll

2022-01-20 01:41 UTC, earlgray283 requested changes
命名規則をある程度固めた方がいいかもしれない(*er は一般に構造体やクラス名に多いと思う)

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +				log.Fatal(err)
systray.Quit() を使ってください

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +				log.Fatal(err)
いや、でもここでプログラムを終了すべきではないですね
定期実行をするプログラムなので、失敗したらリトライなどをすべきです

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +				log.Fatal(err)
systray.Quit() を使ってください

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +			counter, err := a.registerReport()
`count` じゃなくて？

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +		if row.LastSubmitDate.String() == "0001-01-01 00:00:00 +0000 UTC" {
`"0001-01-01 00:00:00 +0000 UTC"` は定数にすべきです

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +func (a *App) registerClassEnq() (int, error) {
regist じゃなくて？

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +		counter, _ := a.registerAll()
ここのエラーハンドリングをきっちりしたいですね

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +				} else {
条件式が真の時に return してるなら else をつける必要は特にないと思います

2022-01-20 01:41 UTC, earlgray283 commented on app/systray-handlers.go
> +		Event := newEvent("["+row.CourseName+"]"+row.Title, row.EndDate)
go は変数や構造体について先頭が大文字か小文字かで public/private を識別しています。
なのでローカル変数に大文字を使うのは良くないです

2022-01-20 01:41 UTC, earlgray283 commented on app/google-calendar-api_test.go
>  	}
カレンダーに予定を追加できるかをテストしているのであれば、AddSchedule を実行後に予定一覧を取得し、追加した予定が含まれているかまでチェックすべきです

2022-01-20 02:52 UTC, mistralll commented on app/systray-handlers.go
> +				log.Fatal(err)
?

2022-01-20 02:53 UTC, mistralll commented on app/systray-handlers.go
> +		counter, _ := a.registerAll()
?

2022-01-20 02:53 UTC, mistralll commented on app/systray-handlers.go
> +				} else {
?

2022-01-20 02:53 UTC, mistralll commented on app/google-calendar-api_test.go
>  	}
とりあえず許して欲しいです（）

2022-01-20 04:42 UTC, Seele0709 commented on app/systray-handlers.go
> +				} else {
done

2022-01-20 04:42 UTC, Seele0709 commented on app/systray-handlers.go
> +		counter, _ := a.registerAll()
done

2022-01-20 08:21 UTC, earlgray283 commented on app/systray-handlers.go
> +				log.Fatal(err)
とりあえず systray.Quit() を使ってください

2022-01-21 06:21 UTC, earlgray283 requested changes

2022-01-21 06:21 UTC, earlgray283 commented on app/systray-handlers.go
> +	added := time.Now().Format("2006-01-02 15:04.05")
`2006-01-02 15:04:05` ではないですか？

2022-01-21 06:21 UTC, earlgray283 commented on app/systray-handlers.go
> +				err := AddSchedule(event, calendarId, a.srv)
これは tips ですが、戻り値が error だけの場合は
```go
if err := AddSchedule(event, calendarId, a.srv); err != nil {
    return -1, err
}
```
でコンパクトに書けます。

2022-01-21 06:21 UTC, earlgray283 commented on app/google-calendar-api_test.go
> +	isAbletoAdd, err := checkDoubleRegisted(event.Summary, event.End, service, calendarId)
isAddable

2022-01-21 06:42 UTC, merged